# Generated by Django 2.2.1 on 2020-01-23 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='coral',
            name='uploader',
        ),
    ]
